### ISSUE TITLE
Support for scripts to install Ubuntu 18.04 LTS (Bionic Beaver)

### ISSUE THREAD

**Issue by sud335** [xen-tools/xen-tools#51] opened 2018-06-28 19:47 UTC
Hi,

The current release version of xen-tools (4.7-1) source package does not have official scripts to install the new dist version Ubuntu-18.04 [https://launchpad.net/ubuntu/bionic/amd64/xen-tools/4.7-1].  Are there any plans to release them soon? Also, is there any alternative method that I can install 18.04 on the new VM.

**Comment by xtaran** [comment] 2018-06-28 23:01
> Are there any plans to release them soon?

Support for Ubuntu 17.10 Artful, Ubuntu 18.04 Bionic and preliminary support for Ubuntu 18.10 Cosmic will be surely part of the next xen-tools release.

I just can't give any promises when that will be. Might be weeks or months. (I need at least half a day to do a proper xen-tools release.)

> Also, is there any alternative method that I can install 18.04 on the new VM.

It probably suffices
* to create a symlink named `bionic.d` pointing to `karmic.d` analogous to other recent Ubuntu releases (`ln -vis karmic.d bionic.d`), and
* to add an entry to `/etc/xen-tools/distributions.conf` analogous to the `zesty` one.

**Comment by zhanghan177** [comment] 2018-07-31 00:48
Thanks for the reply. I tried the above approach and installed Ubuntu 18.04 image. However, the new VM has no network connection upon system bootup.

I think this might have some thing to do with Ubuntu switching to Netplan since 17.10. 

The ethernet interface `eth0` in the 18.04 image shows as `state DOWN`. (also, only `ip` works and no `ifconfig`). After I tried to bring up the eth0, I could only get inet6 address and no internet connection. I have only set up an IPv4 address for the guest and it should get the address through DHCP. Is there something wrong with the bridge networking with the host? The full result is 
```
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether <correct_mac_address> brd ff:ff:ff:ff:ff:ff
    inet6 <some_ip_v6_address> scope link tentative
       valid_lft forever preferred_lft forever
```

Do you have any idea what might have caused the problem? Thanks!

**Comment by prjpet** [comment] 2018-08-07 14:39
Zhanghan177,

First, ifconfig is not a standard part of the Ubuntu distros from 17.04 if I'm correct. Have you tried to manually allocate an IPv4 address using the _ip address add <your ip>/<your mask> dev eth0_ command, that is in the same subnet as the switch? It is working for me... Also, you probably only get a link local IPv6 address allocated to the interface (starting with fe80::) that is not routable, so you will not get internet.

Hope this helps.

**Comment by zhanghan177** [comment] 2018-08-07 17:55
Thanks for the reply.

Manually setting IP addresses doesn't work, unfortunately. However, I worked out a solution to this issue. The root cause is that Ubuntu 18.04 switches to netplan, but the fresh install (from xen-create-image) gives an empty configuration inside `/etc/netplan/`. To solve the problem, I added a default configuration file as
```yaml
# /etc/netplan/01-netcfg.yaml
network:
  version: 2
  renderer: networkd
  ethernets:
    eth0:
      dhcp4: yes
```

After writing that file, run netplan to apply these changes:
```bash
sudo netplan --debug apply
```

And now I have internet access and DHCP resolves properly.

**Comment by arno481** [comment] 2018-08-10 08:48
Hi

would be nice to fix this, we use xen-create-image extensively. Attached is a script to replace 40-setup-networking-deb in /usr/share/xen-tools/bionic.d which supports 18.04's netplan.io. It handles two simple cases: a single static IP and DHCP and creates a /etc/netplan/01-netcfg.yaml for those.

CU,
              Arno and Peter
[40-setup-networking-deb-netplan.txt](https://github.com/xen-tools/xen-tools/files/2277214/40-setup-networking-deb-netplan.txt)

**Comment by fake-name** [comment] 2019-01-11 10:34
For anyone running into this issue, @ arno481's script solves it but you have to set up the builder manually:

Cribbing from the other comments here:

1. *Copy* the ubuntu template dir into a new directory named `bionic.d`

```
cd /usr/share/xen-tools
cp -r karmic.d bionic.d
```
2. add an entry to /etc/xen-tools/distributions.conf as
'''
bionic       = ubuntu     pygrub
'''
3. Replace contents of the `/usr/share/xen-tools/40-setup-networking` with the contents of the `40-setup-networking-deb-netplan.txt` file arno481 provided (or remove it and add the new file, making sure the permissions don't change).

4. create Ubuntu 18.04 image with `--dist=bionic`.

5. Done! Networking should work out-of-the-box now.

------

More generally, what's the status of getting this merged?

**Closed** 2019-02-03 23:54 UTC

**Comment by arno481** [comment] 2020-07-09 10:08
Hi
this problem is back for 20.04. Adding focal to the distributions.conf and linking /usr/share/xen-tools/focal.d to bionic.d appears to work.

**Comment by foxxyz** [comment] 2020-09-04 20:32
> Hi
> this problem is back for 20.04. Adding focal to the distributions.conf and linking /usr/share/xen-tools/focal.d to bionic.d appears to work.

I tried this and ran into the following issue when starting the VM:
```
$ xl create /etc/xen/tester.cfg
Parsing config from /etc/xen/tester.cfg
xc: error: panic: xc_dom_bzimageloader.c:766: xc_dom_probe_bzimage_kernel unable to LZ4 decompress kernel
: Invalid kernel
xc: error: panic: xc_dom_core.c:676: xc_dom_find_loader: no loader found: Invalid kernel
libxl: error: libxl_dom.c:707:libxl__build_pv: xc_dom_parse_image failed: No such file or directory
libxl: error: libxl_create.c:1144:domcreate_rebuild_done: cannot (re-)build domain: -3
libxl: error: libxl.c:1610:libxl__destroy_domid: non-existant domain 19
libxl: error: libxl.c:1568:domain_destroy_callback: unable to destroy guest with domid 19
libxl: error: libxl.c:1495:domain_destroy_cb: destruction of domain 19 failed
```

@arno481 any suggestions? If not perhaps I'll create another issue on here.
